apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-app-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sagar-dave/devops-practice.git
    targetRevision: main
    path: devops-app
    helm:
      valueFiles:
        - ../environments/prod/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
